FIX - CI

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -60,7 +60,7 @@ jobs:
         run: |
           VERSION_REQ=${{ matrix.version }}
           VERSION_CHECK=$(docker run reprostat/octave:${{ matrix.version }} octave --eval "ver Octave" | grep -oP '(?<=GNU Octave Version: )[0-9\.]*')
-          if [[ "xx${VERSION_REQ}xx" != "xx${VERSION_CHECK}xx" ]]; then echo "Version mismatch: required ${VERSION_REQ}, found ${VERSION_CHECK}"; fi
+          if [[ "xx${VERSION_REQ}xx" != "xx${VERSION_CHECK}xx" ]]; then echo "Version mismatch: required ${VERSION_REQ}, found ${VERSION_CHECK}"; exit 1; fi
       - name: Check AWS CLI
         run: |
           docker run reprostat/octave:${{ matrix.version }} aws --version
